# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_room_host_alter_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-updated", "-created"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["-updated", "-created"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
    ]
